[project]
name = "multi-agentic-ai-workshop"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.34",
    "httpx>=0.27",
    "pydantic>=2.7",
    "pydantic-ai-slim[mcp]>=1.0.1",
    "ruff>=0.12.12",
    "tenacity>=9.1.2",
]
